###
GET http://localhost:3000/users

###
POST  http://localhost:3000/create
Content-Type: application/json

###
PUT http://localhost:3000/updateUser/1
Content-Type: application/json

###
PATCH  http://localhost:3000/updateData/1
Content-Type: application/json

###
DELETE  http://localhost:3000/delete/1
